## !USE TEXT THEME
#theme: jekyll-text-theme # Gem-based Jekyll Themes
## => Site Settings
##############################
text_skin: remcustom #  remcustom,"default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: "tomorrow-night-bright" # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
text_color_theme: 
url     : "https://razielgdn.github.io" # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : "/risingembeddedmx" # does not include hostname
title   : "Rising Embedded Mx"
description: > # this means to ignore newlines until "Language & timezone"
  This is my world, where I can do what I think
## => Language and Timezone
##############################
lang: en # the language of your site, default as "en"
timezone: America/Monterrey # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values
## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : Octavio Guendulain
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : Embedded Developer 
  email     : octavioraziel.gdn@gmail.com
  facebook  : profile.php?id=61560642972696 # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : L31zarGdn  # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : octaviorazielgdn # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : razielgdn/risingembeddedmx 
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: razielgdn/risingembeddedmx
repository_tree: main
## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : /archive # "/archive.html" (default)
  blog : /blog # "/blog.html" (default)    
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: false # false (default), true
mathjax_autoNumber:  # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments: 
  provider: gitalk # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : Ov23li1ay2o5ruMov7EU
    clientSecret: 9e8b305791c119712f86399008766dc3d7eb7b62 # GitHub Application Client Secret
    repository  : custom-application-test  # GitHub repo
    owner       : razielgdn # GitHub repo owner
    admin:  # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      - razielgdn #your GitHub Id

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : G-P83G4T9J8J # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - Dockerfile
  - /run-once.sh  
    
  - blog.md

collections_dir: about
collections:
  about:
  output: true

#init projects page  
collections_dir: projects
collections:
  projects:
    output: true
#end projects page

#init 3dprinter zone      
  3dprinting:
    output: true    
#end 3dprinter zone 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true

## projects English
  - scope:
      path: "_projects/en"
    values:
      layout: article
      nav_key: projects
      sidebar:
        nav: projects-en
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      show_date: false
## Spanish Section.
  - scope:
      path: "_projects/es"
    values:
      layout: article
      nav_key: projects-spanish
      sidebar:
        nav: projects-es
      license: false
      aside:
        toc: true
      lang: es-MX  
      show_edit_on_github: false
      show_date: false

## 3d printing zone
  - scope:
      path: "_3dprinting"       
    values:      
      nav_key: 3dprintingZone
      show_date: false  
      sidebar:
        nav: navPrinting   
      aside:
        toc: true   
## end 3dprinting zone     

## Init notes
#   - scope:
#       path: "_projects/en/notes"
#     values:
#       layout: article
#       nav_key: notes
#       sidebar:
#         nav: notes-en
#       license: true
#       aside:
#         toc: true
#       show_edit_on_github: false
#       show_date: false
#       # lightbox: true
#   - scope:
#       path: "_projects/es/notes"
#     values:
#       layout: article
#       nav_key: notas
#       sidebar:
#         nav: notes-es
#       license: true
#       aside:
#         toc: true
#       lang: es_MX
#       show_edit_on_github: false
# #      show_date: false
      # lightbox: true

## End notes

## init about
  - scope:
      path: "about/en"
    values:
      layout: article
      nav_key: about-en
      sidebar:
        nav: about-en
      license: false
      aside:
        toc: true
      lang: en
      show_edit_on_github: false
      show_date: false

  - scope:
      path: "about/es"
    values:
      layout: article
      nav_key: about-es
      sidebar:
        nav: about-es
      license: false
      aside:
        toc: true
      lang: es_MX
      show_edit_on_github: false
      show_date: false    
## end about

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
